#baseurl = "https://blast.pottiri.tech"
#languageCode = "ja-jp"
#languageLang = "ja"
#title = "Cross Blast"
theme = "dream"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
#disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

googleAnalytics = "UA-116125280-1"

# disqusShortname = ""

#enableRobotsTXT = true

hasCJKLanguage = true

# Paginate = 4

defaultContentLanguage = "ja"

[languages]
  [languages.ja]
    baseURL = "https://blast.pottiri.tech"
    title = "くろす・ぶらすと"
    [languages.ja.params]
      author = "くろす・ぶらすと"
      description = "秒で終わる爆弾パズルゲーム"
      headerTitle = "くろす・ぶらすと"
      
  [languages.en]
    baseURL = "https://blast-en.pottiri.tech"
    title = "Cross Blast"
    [languages.en.params]
      author = "Cross Blast"
      description = "A puzzle game that ends in an instant"
      headerTitle = "Cross Blast"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "#f6f6f6"
  backgroundImage = "/background.jpg"
  linkColor = "seagreen"

  # dark mode
  backgroundDark = "black"
  backgroundImageDark = "/background-dark.jpg"
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true

  #images = ["/me/background.jpg"]

  #author = "Cross Blast"
  #description = "A puzzle game that ends in an instant"
  avatar = "/me/me.jpg"
  #headerTitle = "Cross Blast"
  #motto = ""
  categoriesLimitInHeader = 6
  # headerBottomText = ""

  rss = true

  #utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  
  email = "pottiridoubleat@gmail.com"
  twitter = "pottiri_tech"
  #facebook = ""
  instagram = "pottiri_tech"
  # mastodon = ""
  #linkedin = ""
  #github = ""
  #stackoverflow = ""
  #codepen = ""

  siteStartYear = 2020

  favicon = "/me/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = false
  hasTwitterEmbed = true

  # custom css
  customCSS = ["/css/customize.css"]

  titleSeparator = "/bomb/red-bomb.svg"
